# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to deploy'
        # Default value if no value is explicitly provided
        default: 'master'
        # Input has to be provided for the workflow to run
        required: true

      comment:
        description: 'Target repo comment'
        default: 'New code changes'
        required: true

      targetBranch:
        description: 'Target Branch'
        default: 'main'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove .env and Github actions
        run: rm -rf hardcoded-pages && rm -rf .github
      - name: Create Branch
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: nlsltd
          repository_name: res-q
          new_branch_name: ${{ github.event.inputs.targetBranch }}
          access_token: ${{ secrets.API_TOKEN_GITHUB}}
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          user-email: vitalii.nobis@neatbyte.solutions
          commit-message: ${{ github.event.inputs.comment }}
          destination-github-username: 'nlsltd'
          destination-repository-name: 'res-q'
          target-branch: ${{ github.event.inputs.targetBranch }}
